name: notes_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Required for OpenAPI generator
  dio: ^5.9.0
  openapi_generator_annotations: ^6.1.0

  # Optional, for saving tokens
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Required for OpenAPI code generation
  build_runner: ^2.4.8

  openapi_generator: ^6.1.0

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true